services:
  virtualmin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: virtualmin
    hostname: virtualmin.o-leary.com
    ports:
      - "80:80"
      - "443:443"
      - "21:21"
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "2122:2122"
      - "10000:10000"
      - "20000:20000"
      - "53:53"
      - "53:53/udp"
    restart: unless-stopped
